MAINAPP/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	#Leave as empty string for base url
	path('', views.home, name="home"),
	path('register/', views.register,name='register'),
	path('user_login/', views.user_login,name='user_login'),
	path('logout/', views.user_logout,name='logout'),
	path('howitworks/', views.howitworks,name='howitworks'),
	path('contact/', views.contact,name='contact'),
	path('about/', views.about,name='about'),
	path('article/', views.article,name='article'),
	path('<int:id>/read_article/', views.read_article, name="read_article"),
	path('diabetes_risk/', views.diabetes_risk,name='diabetes_risk'),
	path('diabetes_risk_result/', views.diabetes_risk_result,name='diabetes_risk_result'),
	path('cvd_prediction/', views.cvd_prediction,name='cvd_prediction'),
	path('cvd_prediction_result/', views.cvd_prediction_result,name='cvd_prediction_result'),
	path('liver_diagnosis/', views.liver_diagnosis,name='liver_diagnosis'),
	path('liver_diagnosis_result/', views.liver_diagnosis_result,name='liver_diagnosis_result'),
	path('detect_brain_tumor/', views.detect_brain_tumor,name='detect_brain_tumor'),
	path('detect_brain_tumor_result/', views.detect_brain_tumor_result,name='detect_brain_tumor_result'),
	path('search/', views.search,name='search'),
	path('privacy/', views.privacy,name='privacy'),
	path('404/',views.page_not_found),

	path('reset_password/', auth_views.PasswordResetView.as_view(template_name='MAINAPP/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='MAINAPP/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='MAINAPP/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='MAINAPP/password_reset_complete.html'), name='password_reset_complete'),
]

PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MAINAPP.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404="MAINAPP.views.page_not_found"

MAINAPP/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import TextField
from django.utils import timezone

class Article(models.Model):
	posted_on=models.DateField(blank=True,default=timezone.now)
	posted_by =models.CharField(max_length=100,blank=True)
	article_name = models.CharField(max_length= 200)
	article_caption=models.TextField(blank=True)
	article_introduction=models.TextField(blank=True)
	article_sub_heading1 =models.CharField(max_length= 200 ,blank=True)
	article_sub_body1 =models.TextField(blank=True)
	article_conclusion =models.TextField(blank=True)
	article_image = models.ImageField(null=True, blank=True , help_text="crop image as square before upload to get uniform size in the page")
	add_article_to_home = models.BooleanField(default=False,null=True, blank=True ,help_text="Yes will enable to display it on home page")

	def __str__(self):
		return self.article_name

	@property
	def article_imageURL(self):
		try:
			url = self.article_image.url
		except:
			url = ''
		return url


class ContactMessage(models.Model):
	reviewer_name = models.CharField(max_length= 200 ,blank=True)
	reviewer_email=models.EmailField(max_length =200 ,blank=True)
	reviewer_message = models.TextField(max_length=5000,blank=True)

	def __str__(self):
		return self.reviewer_name

class DiagnosisTool(models.Model):
	tool_name = models.CharField(max_length= 200 ,blank=False)
	tool_accuracy = models.CharField(max_length= 200 ,blank=False)
	tool_technology = models.CharField(max_length= 200 ,blank=False)
	tool_detail = models.TextField(max_length=4000,blank=False)
	tool_link = models.CharField(max_length= 200 ,blank=False)
	def __str__(self):
		return self.tool_name

class Subscriber(models.Model):
	subscriber_name = models.CharField(max_length= 300 ,blank=True)
	subscriber_email=models.EmailField(max_length =300 ,blank=True)
	def __str__(self):
		return self.subscriber_name

MAINAPP/forms.py
from django import forms
from django.contrib.auth.models import User
from MAINAPP.models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','username', 'email' , 'password')

class ContactMessageForm(forms.ModelForm):
    class Meta():
        model =  ContactMessage
        fields =('reviewer_name','reviewer_email','reviewer_message',)

class SubscriberForm(forms.ModelForm):
    class Meta():
        model =  Subscriber
        fields =('subscriber_name','subscriber_email',)

MAINAPP/views.py
from django.shortcuts import render
from . import forms
from .models import *
from MAINAPP.forms import UserForm, ContactMessageForm, SubscriberForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
import joblib
import numpy as np


RFClassifierDiabetes=joblib.load('RFClassifierDiabetes.pkl')
RFRegressorDiabetes=joblib.load('RFRegressorDiabetes.pkl')
RFCHeart=joblib.load('RFCHeartModel.pkl')
RFRHeart=joblib.load('RFRHeartModel.pkl')
RFCBrainTumor=joblib.load('RFCBrainTumor.pkl')
RFRBrainTumor=joblib.load('RFRBrainTumor.pkl')
GBClassifierLiver=joblib.load('GBClassifierLiver.pkl')
GBRegressorLiver=joblib.load('GBRegressorLiver.pkl')

# Create your views here.
def home(request):
	subscribe_form = forms.SubscriberForm()
	if request.method =='POST':
		subscribe_form = forms.SubscriberForm(request.POST)
		to = request.POST['subscriber_email']
		subject = 'The Heartbeat'
		body = 'Welcome'+'<p style="font-size:13px;">Thank you for subscribing to The HeartBeat, we are glad to welcome you. The Heartbeat is your intelligent diagnostic expert integrated with widely used machine learning models with up-to 90% of accuracy. We offer variety of tools to predict the presence of diabetes, cardiovascular disease , Brain Tumour & more. Get your hands on our free tools now.</p>'+'<p style="margin-bottom:0px;">Thanks & Regards,</p>'+'<p style="margin-top:2px;"><b>The HeartBeat Team</b></p>'
		msg = EmailMultiAlternatives(subject, body,'mrinalmayank7@gmail.com', [to])
		msg.content_subtype = "html"
		msg.send(fail_silently=False)

		if subscribe_form.is_valid():
			subscribe_form.save()
			messages.info(request,"Successfully subscribed")
			return HttpResponseRedirect(reverse('home'))
		else:
			messages.error(request,"Invalid Details")
			return HttpResponseRedirect(reverse('home'))
	pages = Article.objects.all()
	context = {'pages':pages ,'subscribe_form':subscribe_form}
	return render(request, 'MAINAPP/home.html', context)

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('home'))


def register(request):
	registered = False
	if request.method =='POST':
		user_form =UserForm(data = request.POST)

		if user_form.is_valid():
			 user =user_form.save()
			 user.set_password(user.password)
			 user.save()

			 registered = True
			 messages.info(request,"Successfully Registered")
		else:
			print(user_form.errors)
	else :
		user_form =UserForm
	return render(request ,'MAINAPP/register.html',{'user_form': user_form ,'registered' : registered })



def user_login(request):
	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username , password=password )
		if user:
			if user.is_active:
				login(request , user)
				return HttpResponseRedirect(reverse('home'))

			else:
				return HttpResponse("ACCOUNT NOT ACTIVE")
		else:
			messages.error(request,"Invalid login details.")
			return HttpResponseRedirect("/user_login")
	else:
		return render(request , 'MAINAPP/login.html',{})

def article(request):

	pages = Article.objects.all()
	topics =reversed(Article.objects.all().order_by('id'))
	context = {'pages':pages ,'topics':topics}
	return render(request, 'MAINAPP/article.html', context)

def read_article(request ,id):
	page = Article.objects.get(id=id)
	topics =reversed(Article.objects.all().order_by('id'))
	context = {'page':page ,'topics':topics}
	return render(request, 'MAINAPP/read_article.html', context)

def diabetes_risk(request):
	return render(request, 'MAINAPP/diabetes.html')

def diabetes_risk_result(request):
	if request.method == 'POST':
		Pregnancies=request.POST.get('val1')
		Glucose=request.POST.get('val2')
		BloodPressure=request.POST.get('val3')
		SkinThickness=request.POST.get('val4')
		Insulin=request.POST.get('val5')
		BMI=request.POST.get('val6')
		DiabetesPedigreeFunction=request.POST.get('val7')
		Age=request.POST.get('val8')
	input_data = (Pregnancies ,Glucose ,BloodPressure,SkinThickness ,Insulin ,BMI ,DiabetesPedigreeFunction ,Age)
	input_data_as_numpy_array= np.asarray(input_data)
	input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
	PredictModelRFC = RFClassifierDiabetes.predict(input_data_reshaped)
	PredictModelRFR= RFRegressorDiabetes.predict(input_data_reshaped)*100
	if request.user.is_authenticated :
		userfirstname=request.user.first_name
		risk=str(PredictModelRFR[0])
		if PredictModelRFC[0]==0:
			outcome="Lower chances of diabetes."
		else:
			outcome="Higher risk of diabetes, consult your local medical authority for advice."

		to = request.user.email
		subject = 'The Heartbeat'
		body = 'Hello '+userfirstname+'<p style="font-size:13px;"><b>Thank you for trusting our services, we are sending this email to let you know about the predicted outcomes on the basis of measures provided by you. For any queries drop us a mail at mrinalmayank7@gmail.com</b></p>'+'<p style="font-size:15px;"><b>Measures provided by you :</b></p>'+'Pregnancies. &nbsp;&nbsp;'+Pregnancies+'<br>'+'Glucose. &nbsp;&nbsp;'+Glucose+'<br>'+'Blood Pressure. &nbsp;&nbsp;'+BloodPressure+'<br>'+'Skin Thickness. &nbsp;&nbsp;'+SkinThickness+'<br>'+'Insulin. &nbsp;&nbsp;'+Insulin+'<br>'+'BMI. &nbsp;&nbsp;'+BMI+'<br>'+'Diabetes pedigree func. &nbsp;&nbsp;'+DiabetesPedigreeFunction+'<br>'+'Age. &nbsp;&nbsp;'+Age+'<br>'+'<p style="font-size:18px;text-align:center"><b>Outcomes</b></p>'+'<b>Diabetes Risk</b> &nbsp;&nbsp; '+risk+' % <br>'+'<b>Remarks. &nbsp;&nbsp;</b>'+outcome+'<hr><p style="margin-bottom:0px;">Thanks & Regards,</p>'+'<p style="margin-top:2px;"><b>The HeartBeat Team</b></p>'+'<p style="font-size:13px;color:#A6ACAF;text-align:center;"><i>These outcomes are for informational purposes only, Consult your local medical authority for advice.</i></p>'
		msg = EmailMultiAlternatives(subject, body,'mrinalmayank7@gmail.com', [to])
		msg.content_subtype = "html"
		msg.send(fail_silently=False)

	context={'output1':PredictModelRFR[0] ,'output2':PredictModelRFC[0] ,'p':Pregnancies,'g':Glucose,'bp':BloodPressure,'st':SkinThickness,'insulin':Insulin,'bmi':BMI,'dpf':DiabetesPedigreeFunction,'age':Age}
	return render(request, 'MAINAPP/diabetes.html',context)

def cvd_prediction(request):
	context = {}
	return render(request, 'MAINAPP/heart.html', context)

def cvd_prediction_result(request):
	if request.method == 'POST':
		age=request.POST.get('val1')
		sex=request.POST.get('val2')
		cp=request.POST.get('val3')
		trestbps=request.POST.get('val4')
		chol=request.POST.get('val5')
		fbs=request.POST.get('val6')
		restecg=request.POST.get('val7')
		thalach=request.POST.get('val8')
		exang=request.POST.get('val9')
		oldpeak=request.POST.get('val10')
		slope=request.POST.get('val11')
	input_data = (age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope)
	input_data_as_numpy_array= np.asarray(input_data)
	input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
	PredictRFCHeart= RFCHeart.predict(input_data_reshaped)
	PredictRFRHeart= RFRHeart.predict(input_data_reshaped)*100
	if sex== '1':
		genderText="Male"
	else:
		genderText="Female"

	if fbs== '1':
		fbsText="Yes"
	else:
		fbsText="No"

	if cp== '3':
		cpText="Typical angina"
	elif cp=='2':
		cpText="Non-anginal pain"
	elif cp=='1':
		cpText='Atypical angina'
	else:
		cpText='Asymptomatic'

	if restecg=='2':
		restecgText="Having ST-T wave abnormality"
	elif restecg=='1':
		restecgText="Normal"
	else:
		restecgText="Probable/definite left ventricular hypertrophy"

	if exang=='1':
		exangText ="Yes"
	else:
		exangText ="No"

	if slope=='2':
		slopeText="Upsloping"
	elif slope=='1':
		slopeText="Flat"
	else:
		slopeText="Downsloping"

	if request.user.is_authenticated :
		userfirstname=request.user.first_name
		risk=str(PredictRFRHeart[0])
		if PredictRFCHeart[0]==0:
			outcome="Lower possibility of  cardiovascular disease"
		else:
			outcome="Higher risk of cardiovascular disease, consult your local medical authority for advice."

		to = request.user.email
		subject = 'The Heartbeat'
		body = 'Hello '+userfirstname+'<p style="font-size:13px;"><b>Thank you for trusting our services, we are sending this email to let you know about the predicted outcomes on the basis of measures provided by you. For any queries drop us a mail at mrinalmayank7@gmail.com</b></p>'+'<p style="font-size:15px;"><b>Measures provided by you :</b></p>'+'Age. &nbsp;&nbsp;'+age+'<br>'+'Resting blood pressure. &nbsp;&nbsp;'+trestbps+'<br>'+'Cholesterol. &nbsp;&nbsp;'+chol+'<br>'+'Thalach. &nbsp;&nbsp;'+thalach+'<br>'+'Oldpeak. &nbsp;&nbsp;'+oldpeak+'<br>'+'Gender. &nbsp;&nbsp;'+genderText+'<br>'+'Fasting blood sugar > 120 mg/dl. &nbsp;&nbsp;'+fbsText+'<br>'+'Chest pain type. &nbsp;&nbsp;'+cpText+'<br>'+'Resting electrocardiographic results. &nbsp;&nbsp;'+restecgText+'<br>'+'Exercise induced angina. &nbsp;&nbsp;'+exangText+'<br>'+'Slope of the peak exercise ST segment. &nbsp;&nbsp;'+slopeText+'<br>'+'<p style="font-size:18px;text-align:center"><b>Outcomes</b></p>'+'<b>CVD Risk </b> &nbsp;&nbsp; '+risk+' % <br>'+'<b>Remarks. &nbsp;&nbsp;</b>'+outcome+'<hr><p style="margin-bottom:0px;">Thanks & Regards,</p>'+'<p style="margin-top:2px;"><b>The HeartBeat Team</b></p>'+'<p style="font-size:13px;color:#A6ACAF;text-align:center;"><i>These outcomes are for informational purposes only, Consult your local medical authority for advice.</i></p>'
		msg = EmailMultiAlternatives(subject, body,'mrinalmayank7@gmail.com', [to])
		msg.content_subtype = "html"
		msg.send(fail_silently=False)

templates/MAINAPP/about.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<div class="bground2" style="">
<br><br><br><br><br><br><br>
<div class="container" style="padding:0px 6% 0px 6%;">


  <div class="row">
    <div class="col-lg-6" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;margin-bottom:30px;">
      <div class="" style="padding:1px; background:linear-gradient(to bottom right,rgba(23, 32, 42,0.9) 10% , #000000 35%,#000000 55%, rgba(23, 32, 42,0.9) 90%);">
        <div class=""style="background:black;padding:19px;">
          <p class="logogradient"style="color:white;font-size:40px;margin:0px;text-align:center;font-family: 'Bodoni Moda', sans-serif;">About Us</p>
          <p style="text-align:center;font-size:12px;color:white;margin:10px;">Who we are & why with us ?</p>
          <p style="color:#BDC3C7;font-size:11px;text-align:center;"><label style="margin:0px;color:white;font-weight:600;font-size:12.5px">The Heartbeat</label> is the tech-for-good platform founded with a purpose to make easy, fast and accurate  healthcare diagnosis & services accessible  to all for free and save more lives. We provide clinical decision support to help specialists & doctors to make better decisions quickly with identification of health complications & risk score that are far more precise than the human brain.</p>
          <p style="color:#BDC3C7;font-size:11px;text-align:center;">Our services are completely free with a user centred design & effortless tool usage. We provide 4 diagnostic tools along with healthcare articles for common health complications. The platform is a completely project based website / non-commercial website / non-profitable website.</p>
        </div>
      </div>
    </div>

    <div class="col-lg-6" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;margin-bottom:30px;">
      <div class="" style="padding:1px; background:linear-gradient(to bottom left,rgba(23, 32, 42,0.9) 10% , #000000 35%,#000000 55%, rgba(23, 32, 42,0.9) 90%);">
        <div class=""style="background:black;padding:19px;">
          <p class="logogradient"style="color:white;font-size:40px;margin:0px;text-align:center;font-family: 'Bodoni Moda', sans-serif;">The Lead</p>
          <p style="text-align:center;font-size:12px;color:white;margin:10px;">Meet the founder & deveoper</p>
          <p style="color:#BDC3C7;font-size:11px;text-align:center;"><label style="margin:0px;color:white;font-weight:600;font-size:12.5px">Mrinal Mayank</label> is an eminent developer  & student of Chandigarh University, Punjab pursuing Bachelor of Engineering in Computer Science and Engineering 2019 – 2023. He had completed his AISSCE from Delhi Public School,Ranchi, Jharkhand in the Year 2019. He is experienced in Full Stack Web Development , Supervised Machine Learning , data Mining with relevant projects and research works . Holding a good command over programming languages, and working on real world problems. </p>
          <p style="color:#BDC3C7;font-size:11px;text-align:center;">The project “The HeartBeat”  is solely developed by Mrinal  as an integral part of  his learning experience & training which is an authenticated record of his original piece of work. </p>
        </div>
      </div>
    </div>

    <div class="col-lg-5 col-md-12 col-sm-12 col-12" style="margin-left:auto;margin-right:auto;">
      <div class="" style="width:100%;padding:20px;">
        <p style="color:white;font-size:40px;font-weight:600;font-family: 'Bodoni Moda', sans-serif;">You’re not alone and help is at your hand.</p>
        <p style="font-size:13px;color:white;">Providing clinical decision support specialized with intelligent diagnostic ML tools. </p>
        <p ><a  class="glowicon"href="{% url 'howitworks'  %}" style="border-radius:30px;font-size:15px;font-weight:700;border:0px;color:white;"> Get Started<i class="bi bi-chevron-right"></i></a></p>

      </div>
    </div>
    <div class="col-lg-7 col-md-12 col-sm-12 col-12" style="margin-left:auto;margin-right:auto;">
      <div class="" style="width:100%;background-image:url('{% static 'images/dev.jpg'%}');background-size:100%;background-repeat: no-repeat;height:100vh;width:100%;padding:30px;">
        <br>
        <p style="text-align:right;color:black;font-size:12.5px;font-weight:700;margin:0px;">Mrinal Mayank</p>
        <p style="text-align:right;color:black;font-size:12px;font-weight:400;margin:0px;">Full Stack Developer</p>
        <p style="text-align:right;color:grey;font-size:12px;font-weight:400;margin:0px;"><i>Founder. The HeartBeat</i></p>
      </div>
    </div>

  </div>

</div>
</div>

{% endblock content %}

templates/MAINAPP/contact.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<div class="bground2" style="background-image:url('{% static "images/img5.jpg"%}') ;">
<br><br><br><br><br><br><br>
<div class="container">
  <div class="col-lg-9 col-md-12 col-sm-12 col-12" style="margin-right:auto;margin-left:auto;padding-bottom:100px;">

<div class="navbackdrop" style="margin-right:auto;margin-left:auto;border:5px solid white;border-radius:30px;background:rgba(255,255,255,0.08);"data-aos="zoom-in">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-12" style="display:flex;flex-wrap:wrap;margin-left:auto;margin-right:auto;position:relative;">
      <div class="" style="width:100%;padding:20px;">
        <p style="font-size:18px;font-weight:400;color:white;font-family:'Codystar', cursive;text-align:center;">The HeartBeat</p>
        <p style="font-size:12px;text-align:center;color:white">We'd love to hear from you, Feel free to contact us for any queries or suggestions.</p>
        <hr color="#1C2833" style="margin:8px;margin-bottom:20px;">
        <br>
        <p style="font-size:13px;color:white;margin:2px;"><label ><a href="tel:7858832086"><i class="bi bi-telephone-fill" style="font-size:15px;"></i></a></label> 7858832086</p>
        <p style="font-size:13px;color:white ;margin:2px;"> <label ><a href="mailto:mrinalmayank7@gmail.com"><i class="bi bi-envelope-fill"style="font-size:15px;"></i></a></label> mrinalmayank7@gmail.com</p>
        <p style="font-size:13px;color:white ;margin:2px;">Reach Us - Upper Bazar, Near Trade Center,  Ranchi, Jharkhand 834001</p>
   <br><br>
   <div class="icons text-center" style=" position: absolute;bottom:5px;margin-right:auto;margin-left:auto; left:0;right:0;">
    <label ><a href="https://www.linkedin.com/in/mrinal-mayank-bb3112200/"><i class="bi bi-linkedin"
    style="margin:7px;font-size:18px;"></i></a></label>
    <label ><a href="https://github.com/mrinalmayank7/"><i class="bi bi-github"
    style="margin:7px;font-size:20px;"></i></a></label>
    <label ><a href="https://www.instagram.com/mrinalmayank7/"><i class="bi bi-instagram"
       style="margin:7px;font-size:20px;"></i></a></label>
    </div>
    </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-12" style="display:flex;flex-wrap:wrap;margin-left:auto;margin-right:auto;">
      <div class="" style="width:100%;background:linear-gradient(to right ,#E6E6FA 20% , #B0C4DE 60% );border-radius:24px;padding:20px;">
        <p style="text-align:center;font-family: 'Bodoni Moda', serif;font-size:20px;color:black">Write to Us</p>
      <form class=""  method="POST" enctype="multipart/form-data" action ="{% url 'contact' %}">
        {% csrf_token %}
        <label for="id_reviewer_name" style="font-size:13px;font-weight:700;margin:5px;color:black;">Name</label>
        <input type="text" class="form-control" id ="id_reviewer_name" name="reviewer_name"  style="background:#F0F8FF;border:0px;border-radius:50px;font-size:13px;color:black;font-weight:700;margin-bottom:0px;" required>
        <br>
        <label for="id_reviewer_email" style="font-size:13px;font-weight:700;margin:5px;color:black;">Email</label>
        <input type="email" class="form-control" id ="id_reviewer_email"name="reviewer_email"  style="background:#F0F8FF;border:0px;border-radius:50px;font-size:13px;color:black;font-weight:700;margin-bottom:0px;" required>
        <br>
        <label for="id_reviewer_message" style="font-size:13px;font-weight:700;margin:5px;color:black;">Message</label><br>
        <div class="text-center">
        <textarea class="form-control" name="reviewer_message"  id="id_reviewer_message" style="border:0px;border-bottom:1px solid #A9A9A9;
        width:100%;height:70px;font-size:12px;padding:5px;resize: none;background:transparent;border-radius:0px;"></textarea>
        </div>
        <br>
        {% for message in messages %}

          <p style="text-align:center;color:green;font-size:13px">{{message}}</p>

        {% endfor %}
        <div class="text-center">
          <button type="submit" class="btn btn-outline-primary" style="border-radius:50px;font-weight:600;font-size:15px;border-width:2px">Submit </button>
        </div>
        </form>
       </div>
    </div>
  </div>
</div>

</div>
</div>
</div>

{% endblock content %}

templates/MAINAPP/password_reset.html
{%  extends 'MAINAPP/home.html' %}
{% load static %}
{% block content %}
<div class="" style="background-color:#000515 ;">
<br><br><br><br><br><br>
<div class="container" style="padding-bottom:150px;">
  <div class="row">

    <div class="col-lg-6 col-md-9 col-sm-12 col-12" style="margin-left:auto;margin-right:auto;display:flex;flex-wrap:wrap;">
      <div class="" style="width:100%;padding:5%">
        <p style="font-size:50px;color:white;text-align:center">Reset Password</p>
        <hr color="#1C2833" style="margin:8px;margin-bottom:20px;">
        <p style="font-size:13px;text-align:center;color:#BFC9CA;">Please write the <b>registered email </b>
        which is linked to your account to reset the password.</p>

        <form method="post">
          {% csrf_token %}

          <div style="padding:20px;">
            <p style="color:white;font-size:16px;font-weight:600;">Email Address</p>
          <input type="email" class="form-control"name="email"  style="background:white;border-width:0px;font-size:14px;border-radius:30px;" required>
          </div>
          <br>
          <div class="text-center">
          <input type="submit" class="btn btn-outline-primary text-center"
          href="templates/MAINAPP/password_reset_sent.html"value=" Send reset link " style="font-size:15px;border-radius:40px;border-width:2px;font-weight:600;">
          </div>
        </form>


      </div>
    </div>
  </div>
</div>
</div>

{% endblock content %}